services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK=022
    volumes:
      - /home/debrid/docker/DUMB/data/prowlarr:/config
    ports:
      - "9696:9696"
    network_mode: bridge
    security_opt:
      - no-new-privileges:true
    restart: always

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: rd_sonarr
    hostname: rd_sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK=022
    volumes:
      - /home/debrid/docker/DUMB/data/sonarr:/config
      - /home/debrid/docker/DUMB/mnt/debrid:/mnt/debrid:rslave
    ports:
      - "8989:8989"
    network_mode: bridge
    security_opt:
      - no-new-privileges:true
    restart: always

  radarr:
    image: linuxserver/radarr:latest
    container_name: rd_radarr
    hostname: rd_radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK=022
    volumes:
      - /home/debrid/docker/DUMB/data/radarr:/config
      - /home/debrid/docker/DUMB/mnt/debrid:/mnt/debrid:rslave
    ports:
      - "7878:7878"
    network_mode: bridge
    security_opt:
      - no-new-privileges:true
    restart: always

  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - BASE_URL=/ #optional
    volumes:
      - /home/debrid/docker/DUMB/data/ombi
    ports:
      - 3579:3579
    restart: unless-stopped


